name: "Packaging (el9)"

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: RPM Packaging
    runs-on: ubuntu-22.04
    container: rockylinux:9
    steps:
      - name: Install Dependencies
        run: |
          cat /etc/redhat-release
          yum -y install git rpm-build rpm-sign rsync make gcc libusb1-devel

      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Package RPM
        run:
          make package

      - name: Clone Package Repository
        uses: actions/checkout@v3
        with:
          repository: rockit-astro/packages
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: packages

      - name: Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run:
          packages/sign-and-push-packages.sh *.rpm

